export enum ActionType {
	SET_INITIALIZATION = "app/SET_INITIALIZATION",
	SET_ERROR_MESSAGE = "app/SET_ERROR_MESSAGE",

	SET_HEADER_IMAGE = "header/SET_HEADER_IMAGE",
	SET_BURGER = "header/SET_BURGER",

	SET_AUTH_USER = "login/SET_AUTH_USER",
	NOT_AUTH_USER = "login/NOT_AUTH_USER",

	SET_PROFILE = "profile/SET_PROFILE",
	ADD_POST = "profile/ADD_POST",
	DELTE_POST = "profile/DELTE_POST",
	SET_POSTS = "profile/SET_POSTS",
	SET_POSTS_TOTAL_COUNT = "users/SET_POSTS_TOTAL_COUNT",
	LIKE_POST = "profile/LIKE_POST",
	UNLIKE_POST = "profile/UNLIKE_POST",

	SEND_MESSAGE = "messages/SEND_MESSAGE",

	SET_WHOSE_FRIENDS = "friends/SET_WHOSE_FRIENDS",
	SET_FRIENDS = "friends/SET_FRIENDS",
	SET_FRIENDS_TOTAL_COUNT = "friends/SET_FRIENDS_TOTAL_COUNT",

	FOLLOW = "users&profile&friends/FOLLOW",
	UNFOLLOW = "users&profile&friends/UNFOLLOW",

	SET_USERS = "users/SET_USERS",
	SET_USERS_TOTAL_COUNT = "users/SET_USERS_TOTAL_COUNT",

	SET_THEME = "settings/SET_THEME",
}
